### PR TITLE
mrc-3066 upgrade gradle

### PR DESCRIPTION
**Pull request by hillalex**
Upgrades to the latest gradle version. This required the following changes:
* using a new docker plugin, as the other one has been abandoned and is not compatible with gradle 7
* a  syntax change to the jacoco plugin
* some more explicit "dependsOn" declarations

### CODE REVIEW

**Review by EmmaLRussell — COMMENTED** [review]
LGTM, as far as I can tell! Works for me in dev, but that's not really giving the docker changes a workout. Did you try deploying this branch to UAT, or shall I try that?

**Comment by hillalex** [comment]
> LGTM, as far as I can tell! Works for me in dev, but that's not really giving the docker changes a workout. Did you try deploying this branch to UAT, or shall I try that?

ah yeah good point, will deploy this and the api as well to UAT

**Comment by hillalex** [comment]
No sorry, it's expected to fail, I'm in the middle of adding a smoke test for the cli!

**Review by EmmaLRussell — APPROVED** [review]
Works for me!

**Review by Nicolas-Dolan — APPROVED** [review]

**Pull request merged**
