### PR TITLE
mrc-2947 linting and vscode support

### PR DESCRIPTION
**Pull request by hillalex**
The other branch was min-named so recreating this PR; previous comments were here: https://github.com/vimc/orderly-web/pull/434

@Nicolas-Dolan I know we didn't get to the bottom of why the VSCode settings weren't working for you but I'd like to get this merged for the linting at least, and then perhaps we can do some more debugging of your setup in person next week!

### CODE REVIEW

**Comment by hillalex** [comment]
(nb build failing pending selenium tests fix)

**Review by EmmaLRussell — COMMENTED** [review]
Seems like a nice set of rules for keeping the markup clean. Can't really comment on the VSCode settings. 

Would it be worth including fix and no-fix npm lint tasks?

**Comment by hillalex** [comment]
> Seems like a nice set of rules for keeping the markup clean. Can't really comment on the VSCode settings.
> 
> Would it be worth including fix and no-fix npm lint tasks?

It's pretty easy to use the `fix` option, just run `npm run lint -- --fix`. But I'll add this to the README!

**Review by Nicolas-Dolan — COMMENTED** [review]
I'm still having the same formatting issues as before with this but I think that was to be expected. 

I'm a little concerned this is going to cause a bunch of conflicts for my incoming PRs as I've done some major refactoring and it's a lot more work for me to address those conflicts than it is to run an autoformatter after my changes have been merged.

**Comment by hillalex** [comment]
> I'm still having the same formatting issues as before with this but I think that was to be expected.
> 
> I'm a little concerned this is going to cause a bunch of conflicts for my incoming PRs as I've done some major refactoring and it's a lot more work for me to address those conflicts than it is to run an autoformatter after my changes have been merged.

There will be conflicts on one branch no matter which order these are merged in, but the thing to do is just to keep your version of the conflicted files, then run the autoformatter/linter on them.

**Comment by Nicolas-Dolan** [comment]
> > I'm still having the same formatting issues as before with this but I think that was to be expected.
> > I'm a little concerned this is going to cause a bunch of conflicts for my incoming PRs as I've done some major refactoring and it's a lot more work for me to address those conflicts than it is to run an autoformatter after my changes have been merged.
> 
> There will be conflicts on one branch no matter which order these are merged in, but the thing to do is just to keep your version of the conflicted files, then run the autoformatter/linter on them.

My autoformatter does not work with vue files but I guess I could just dismiss the conflicts and move on.

**Comment by hillalex** [comment]
> My autoformatter does not work with vue files but I guess I could just dismiss the conflicts and move on.

Oh I see what you mean, you can't format the files at all. This is a massive pain and we should definitely sit down in person next week to sort it out. In the meantime I can pull down your branches and handle the merge/fix any formatting issues once you are ready to submit the PRs.

**Review by EmmaLRussell — APPROVED** [review]

**Review by Nicolas-Dolan — APPROVED** [review]

**Pull request merged**
