### PR TITLE
mrc-2808 Dummy endpoint with full schema for summary page

### PR DESCRIPTION
**Pull request by Nicolas-Dolan**
_Before submitting please review
the [PR checklist](https://mrc-ide.myjetbrains.com/youtrack/articles/RESIDE-A-13/Pull-Request-guidelines)_

To test, add the below code to the mounted in `runWorklfowProgress.vue`
```
api.post(`/workflows/summary`, {
                        reports: [],
                        ref: null
                    })
                    .then((data) => {
                        console.log("data", data)
                    })
                    .catch((error) => {
                        console.log("error", error)
                    })
```

I'm not sure why the build is failing on the build CSS generator.

Keep getting this error. Is the schema deployed on orderly sever?
image

### CODE REVIEW

**Review by EmmaLRussell — COMMENTED** [review]
Referring to our earlier discussion,  I guess this needs to be a POST now. 

Can we include an integration test which checks that this satisfies the expected schema using `validateAgainstSchema` (e.g. see tests like [this](https://github.com/vimc/orderly-web/blob/168f77f301189989346cbb8b20049babc658f06a/src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/api/ReportTests.kt#L20))

**Comment by Nicolas-Dolan** [comment]
> Referring to our earlier discussion, I guess this needs to be a POST now.
> 
> Can we include an integration test which checks that this satisfies the expected schema using `validateAgainstSchema` (e.g. see tests like [this](https://github.com/vimc/orderly-web/blob/168f77f301189989346cbb8b20049babc658f06a/src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/api/ReportTests.kt#L20))

@EmmaLRussell Keep getting this error for the added integration test. It doesn't seem to be able to find the schema on orderly server. The schema is merged into master but is it deployed on orderly sever?
image

**Comment by EmmaLRussell** [comment]
> > Referring to our earlier discussion, I guess this needs to be a POST now.
> > Can we include an integration test which checks that this satisfies the expected schema using `validateAgainstSchema` (e.g. see tests like [this](https://github.com/vimc/orderly-web/blob/168f77f301189989346cbb8b20049babc658f06a/src/app/src/test/kotlin/org/vaccineimpact/orderlyweb/tests/integration_tests/tests/api/ReportTests.kt#L20))
> 
> @EmmaLRussell Keep getting this error for the added integration test. It doesn't seem to be able to find the schema on orderly server. The schema is merged into master but is it deployed on orderly server? image

Hm, that's odd. Shouldn't be anything to do with orderly server 'deploy' - you're testing with orderly server deployed locally. It's obviously finding `WorkflowSummaryResponse` ok (so shouldn't be a github perms issue or anything lihe that) but then it's not able to find the `WorkflowReports` schema which is referenced from there. Not sure why that would be - the $ref looks right to me...

**Comment by EmmaLRussell** [comment]
..although, it doesn't look like we have any other workingexamples which use a schema with a $ref..

**Comment by EmmaLRussell** [comment]
OK, I think the current JSONValidator doesn't support schemas with $refs -  in HINT we use a [custom schema read factory](https://github.com/mrc-ide/hint/blob/dd6bac39074f8b781dd214bc065e40d01619354f/src/app/src/test/kotlin/org/imperial/mrc/hint/helpers/JSONValidator.kt#L28) to resolve schemas, but doesn't look to me like we're doing that in OW yet. It would be great to add that in, but since this ticket is pretty critical path, that should probably happen in another ticket, and in this one maybe just do checking in the test that it's the expected shape, with a note that schema check will be added when that ticket is implemented. Does that sound ok?

**Pull request closed without merging**
